### ISSUE TITLE
Run_time_analysis

### ISSUE THREAD

**Issue by giangdao1402** [JokerJohn/SLAMTools#2]
Hi @JokerJohn 
Thank for you useful work !
I have a question: What are those values in .txt file of Run_time_analysis folder.
Thank you !!!

**Comment by JokerJohn** [comment]
just see the following notes in readme
![image](https://github.com/JokerJohn/SLAMTools/assets/25702851/2e79c8b1-61ad-46b8-90f3-4cae77a27c7b)

**Comment by giangdao1402** [comment]
Great !
Thank you !
